ProductDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from pages.views import home_view, contact_view, about_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('contact/', contact_view, name='contact'),
    path('about/', about_view, name='about'),

    path('products/', include('products.urls')),
    path('blog/', include('blog.urls')),
    path('course/', include('course.urls'))
]

blog/urls.py
from django.urls import path
from blog.views import (
    article_details,
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView,
)

app_name = 'blog'
urlpatterns = [
    path('', ArticleListView.as_view(), name='article_list'),
    path('create/', ArticleCreateView.as_view(), name='article_create'),
    path('<int:id>/details', ArticleDetailView.as_view(), name='article_detail'),
    path('<int:id>/update', ArticleUpdateView.as_view(), name='article_update'),
    path('<int:id>/delete', ArticleDeleteView.as_view(), name='article_delete'),
    path('details/', article_details, name='article_details')
]

blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Blog(models.Model):
    title   = models.CharField(max_length=120)
    content = models.TextField()
    active  = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse("blog:article_detail", kwargs={'id': self.id})

blog/forms.py
from django import forms

from .models import Blog

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Enter title'
            }
        )
    )
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'materialize-textarea',
                'placeholder': 'Enter blog content'
            }
        )
    )
    class Meta:
        model = Blog
        fields = [
            'title',
            'content',
            'active'
        ]

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    ListView,
    DeleteView
)

from .forms import ArticleForm
from .models import Blog
# Create your views here.

class ArticleListView(ListView):
    template_name = 'blog/article_list.html'
    queryset = Blog.objects.all()

class ArticleDetailView(DetailView):
    template_name = 'blog/article_detail.html'
    queryset = Blog.objects.all()               #not needed. but filters the data before returning selecting/filtering

    def get_object(self):
        id_ = self.kwargs.get("id")             #self.kwargs are passed in from the url
        return get_object_or_404(Blog, id=id_)

class ArticleCreateView(CreateView):
    template_name = 'blog/article_create.html'
    form_class = ArticleForm
    queryset = Blog.objects.all()
    # success_url = '/blog'

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

    #def get_success_url(self):
    #    return '/blog'

class ArticleDeleteView(DeleteView):
    template_name = 'blog/article_delete.html'
    
    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Blog, id=id_)

    def get_success_url(self):
        return reverse('blog:article_list')
        
class ArticleUpdateView(UpdateView):
    template_name = 'blog/article_create.html'
    form_class = ArticleForm
    queryset = Blog.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Blog, id=id_)

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

def article_details(request):
    form = ArticleForm(request.POST or None)

    if form.is_valid():
        form.save()
        form = ArticleForm()

    context = {
        'form': form
    }
    return render(request, "blog/article_details.html", context)

blog/templates/blog/article_create.html
{% extends 'base.html' %}

{% block content%}
<form method="POST"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn waves-effect waves-light">Add<i class="material-icons right">send</i></button>
</form>
{% endblock %}

blog/templates/blog/article_delete.html
{% extends 'base.html' %}

{% block content%}
<form method="POST"> {% csrf_token %}
    <h1>Do you want to delete the post {{object.title}}?</h1>
    <p><input type="submit" value="Yes"><a href="../">Cancel</a></p>
</form>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ object.title }}</h1>
<p>{{ object.content }}</p>
<a class="btn waves-effect waves-light" href="{% url 'blog:article_update' object.id %}">Edit</a>
{% endblock %}

blog/templates/blog/article_details.html
{% extends 'base.html' %}

{% block content %}
<h1>Article</h1>

<form method="POST"> {% csrf_token %}
    {{ form.as_p}}
    <button type="submit" class="btn waves-effect waves-light">Add<i class="material-icons right">send</i></button>
</form>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Article List View</h1>

{% for obj in object_list %}
    <p>{{ obj.name }} - <a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></p>
{% endfor %}

{% endblock %}