ProductDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from pages.views import home_view, contact_view, about_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('contact/', contact_view, name='contact'),
    path('about/', about_view, name='about'),

    path('products/', include('products.urls')),
    path('blog/', include('blog.urls')),
    path('course/', include('course.urls'))
]

blog/urls.py
from django.urls import path
from blog.views import (
    article_details,
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView,
)

app_name = 'blog'
urlpatterns = [
    path('', ArticleListView.as_view(), name='article_list'),
    path('create/', ArticleCreateView.as_view(), name='article_create'),
    path('<int:id>/details', ArticleDetailView.as_view(), name='article_detail'),
    path('<int:id>/update', ArticleUpdateView.as_view(), name='article_update'),
    path('<int:id>/delete', ArticleDeleteView.as_view(), name='article_delete'),
    path('details/', article_details, name='article_details')
]

products/urls.py
from django.urls import path
from products.views import products_view, product_create_view, product_lookup_view, render_initial_data

app_name = 'products'
urlpatterns = [
    path('', products_view, name='products'),
    # path('', render_initial_data, name='products'),
    path('create/', product_create_view, name='product_create'),
    path('details/<int:id>/', product_lookup_view, name='product_lookup'),
    path('details/<int:id>/', product_lookup_view, name='product_details')
]

products/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Product(models.Model):
    title           = models.CharField(max_length=120)
    description     = models.TextField(blank=True, null=False)
    price           = models.DecimalField(decimal_places=2, max_digits=100)
    summary         = models.TextField(blank=True)
    featured        = models.BooleanField(null=True)

    # def get_absolute_url(self):
    #     return f"/products/{self.id}/"

    def get_absolute_url(self):
        return reverse("products:product_details", kwargs={'id': self.id})

products/forms.py
from django import forms

from .models import Product

class ProductCreateForm(forms.ModelForm):   # only .ModelForm can use instance
    class Meta:
        model = Product
        fields = [
            'title',
            'description',
            'price'
        ]

class ValidatedProductForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder' : "Enter product name"
            }
        )
    )
    email = forms.EmailField()
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'id': "product-desp",
                'placeholder': "Enter product description",
                'class': "materialize-textarea",
                'rows': 5,
                'cols': 500
            }
        )
    )
    price = forms.DecimalField(initial=1.99)

    class Meta:
        model = Product
        fields = [
            'title',
            'description',
            'price'
        ]

    def clean_title(self, *args, **kwargs):
        title = self.cleaned_data.get("title")
        if not "CFE" in title:
            raise forms.ValidationError("This is not a valid title. Make sure your title contains 'CFE'.")
        else:
            return title
    
    def clean_email(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        if not email.endswith("edu"):
            raise forms.ValidationError("This is not a valid email")
        else:
            return title

class RawProductForm(forms.Form):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder' : "Enter product name"
            }
        )
    )
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'id': "product-desp",
                'placeholder': "Enter product description",
                'class': "materialize-textarea",
                'rows': 5,
                'cols': 500
            }
        )
    )
    price = forms.DecimalField(initial=1.99)
    featured        = forms.BooleanField()

products/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect

from .models import Product
from .forms import ProductCreateForm, RawProductForm, ValidatedProductForm
# Create your views here.
def products_view(request, *args, **kwargs):
    obj = Product.objects.all().order_by('id').first()
    
    form = ValidatedProductForm(request.POST or None)

    if form.is_valid():
        form.save()
        form = ValidatedProductForm()

    queryset = Product.objects.all()

    context = {
        'form': form,
        "object_list": queryset,
        'id': obj.id
    }
    return render(request, "products.html", context)

def product_create_view(request): #Using built in django 'automated' forms
    initial_data = {
        'title': "This is an initial product name"
    }
    obj = Product.objects.get(id=1)
    # form = ProductCreateForm(request.POST or None, instance=obj) #changes database data
    form = ProductCreateForm(request.POST or None)

    if form.is_valid():
        form.save()
        form = ProductCreateForm()

    context = {
        'form': form
    }

    return render(request, "products/product_create.html", context)

def product_lookup_view(request, id):
    # obj = get_object_or_404(Product, id=id)
    try:
        obj = Product.objects.get(id=id)
        next_obj= Product.objects.filter(id__gt=obj.id).order_by('id').first()
        prev_obj= Product.objects.filter(id__lt=obj.id).order_by('-id').first()
    except Product.DoesNotExist:
        raise Http404

    if request.method == "POST":
        print(id)
        obj.delete()
        return redirect('/products')

    context = {
        'object' : obj,
        'prev_product_id' : prev_obj.id if prev_obj else 1,
        'next_product_id' : next_obj.id if next_obj else obj.id
    }
    return render(request, "products/product_lookup.html", context)

# def product_create_view(request):   #raw HTML Form Example
#     print(request.GET)
#     print(request.POST)
#     if request.method == 'POST':
#         title = request.POST.get('title')
#         print(title)
#     context = {
#     }

#     return render(request, "products/product_create.html", context)

# def product_create_view(request):   #pure HTML Form Example
#     form = RawProductForm()
#     if request.method == 'POST':
#         form = RawProductForm(request.POST)
#         if form.is_valid():
#             print(form.cleaned_data)
#             Product.objects.create(**form.cleaned_data)
#         else:
#             print(form.errors)
#     context = {
#         'form': form
#     }

#     return render(request, "products/product_create.html", context)

def render_initial_data(request):
    initial_data = {
        'title': "This is an initial title"
    }
    initial_obj = Product.objects.get(id=1)
    form = ProductCreateForm(request.POST or None, initial=initial_data, instance=initial_obj)
    
    if form.is_valid():
        form.save()
    
    context = {
        'form': form
    }
    return render(request, "products.html", context)

templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title|safe }}</h1>
<p>Phone number: {{ phone_number }}</p>
<ul class="collection with-header">
    <li class="collection-header grey lighten-2">My Hobbies</li>
{% for hobby in hobbies %}
    <li class="collection-item">{{ forloop.counter}}. {{ hobby }}</li>
{% endfor %}
</ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Sample Django</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% include 'header.html' %}
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block content %}
<h1>Contact Page!</h1>
<p>This is a template</p>
{% endblock %}

templates/header.html
{% load static %}
{% comment %} MaterializeCSS {% endcomment %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
{% comment %} Custom CSS/JS {% endcomment %}
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<img class="full-width" src="{% static 'img/home_page_parallax.jpg' %}">
<h1 class="grey-text text-darken-3">TDjango Supermarketing</h1>
<p>Hello {{ request.user|capfirst }}!</p>
<a class="waves-effect waves-light btn" href="admin/">Go to Admin<i class="material-icons right">person</i></a>
{% endblock%}

templates/navbar.html
<nav class="cyan">
    <div class="nav-wrapper">
        <a href="/" class="left brand-logo" style="padding-left:10px"><i class="material-icons">shopping_basket</i>TDjango</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="right">
            <li><a href="/">Home</a></li>
            <li><a href="/products">Product</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="/contact">Contact</a></li>
            <li><a href="/blog">Blog</a></li>
            <li><a href="/course">Course</a></li>
        </ul>
    </div>
</nav>

<ul class="sidenav" id="mobile-demo">
    <li><a href="/">Home</a></li>
    <li><a href="/products">Product</a></li>
    <li><a href="/about">About</a></li>
    <li><a href="/contact">Contact</a></li>
    <li><a href="/blog">Blog</a></li>
    <li><a href="/course">Course</a></li>
</ul>

templates/products.html
{% extends 'base.html' %}

{% block content %}
<h1>Products Page!</h1>
<p>This is a template</p>
<!-- <a class="waves-effect waves-light btn" href="/create">Create</a> -->
<a class="waves-effect waves-light btn modal-trigger" href="#add-modal">Create</a>
<a class="waves-effect waves-light btn" href="{% url 'products:product_lookup' id %}">View</a>

<ul class="collection">
{% for obj in object_list %}
    <li class="collection-item"><a href="{{ obj.get_absolute_url }}">{{ obj.id }}. {{ obj.title}}</a></li>
{% endfor %}
</ul>

<div id="add-modal" class="modal">
    <form method="POST"> {% csrf_token %}
        <div class="modal-content">
            <h4>Add New Product</h4>
            {{ form.as_p }}
        </div>
        <div class="modal-footer">
            <button class="btn modal-close waves-effect waves-light">Close</button>
            <button type="submit" class="btn modal-close waves-effect waves-light">Add<i class="material-icons right">send</i></button>
        </div>
    </form>
</div>
{% endblock %}